global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: "uptime"
    scrape_interval: 30s
    scheme: http
    metrics_path: "/metrics"
    static_configs:
        - targets: ["uptime-kuma:3001"]
    basic_auth:
        username: kuma_username
        password: kuma_password
