aservices:
  grafana:
    image: grafana/grafana-oss
    environment:
      - SERVICE_FQDN_GRAFANA_3000
      - 'GF_SERVER_ROOT_URL=${SERVICE_FQDN_GRAFANA}'
      - 'GF_SERVER_DOMAIN=${SERVICE_FQDN_GRAFANA}'
      - 'GF_SECURITY_ADMIN_PASSWORD=${SERVICE_PASSWORD_GRAFANA}'
    volumes:
      - rafana-data:/var/lib/grafana
      - ~/grafana_configs/datasources.yml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - ~/grafana_configs/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yaml:ro
      - ~/grafana_configs/dashboard.json:/var/lib/grafana/dashboards/dashboard.json:ro
    ports:
      - "9100:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/api/health"]
      interval: 5s
      timeout: 20s
      retries: 10

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9110:9090"
    volumes:
      - ~/grafana_configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9120:9100"
    command:
      - '--path.rootfs=/host'
    volumes:
      - /:/host:ro,rslave