services:
  it-tools:
    image: 'corentinth/it-tools:latest'
    environment:
      - SERVICE_FQDN_ITTOOLS_80
    volumes:
      - 'it-tools-data:/app/data'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:80'
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "9000:80"
